### PR TITLE
bug: added Proper Title on Events page

### LINKED ISSUE #199: TITLE 2 instead of proper title in events tab
### Describe the bug

Events tab has placeholder text "TITLE 2" instead of proper title.

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on events
3. See there is `TITLE 2`

### Expected behavior
There should be a proper title

### Screenshots
Screenshot 2021-01-25 at 20 24 40

### Desktop (please complete the following information):
 - OS: any
 - Browser any
 - Version any

### Smartphone (please complete the following information):
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

### PR DESCRIPTION
**Pull request by Amulya-coder**
### Description
Changed TITLE 2 to `Benefits`

Fixes #199 

### Type of Change:
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

image

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by isabelcosta** [comment]
@Amulya-coder why did you put Benefits? I am asking because I am not aware of what is supposed to be there :)

**Comment by Amulya-coder** [comment]
@isabelcosta  the website didn't mention about the Benefits so I feel it will be good to say about the Benefits also right under the Events section currently EVENTS and TITLE2 section have the same description but it will be getting to change in future according to TITLE2. Please let me know your suggestions regarding this :)

**Comment by annabauza** [comment]
yeah Benefits doesn't sounds right. Maybe we can find the original issue? I only found this design
EventsPageDesign-Simran Shilky

**Comment by annabauza** [comment]
Also the other title is in caps.

**Comment by annabauza** [comment]
Just saw same image is twice, sorry for confusion, but I think we should remove this title and second image and keep just 2 paragraphs for one image.

**Comment by Amulya-coder** [comment]
> Just saw same image is twice, sorry for confusion, but I think we should remove this title and second image and keep just 2 paragraphs for one image.

Yes, we can remove the second title and image and keep the paragraphs right below the main title (Events),  so for this implementation, we have to open a new issue right?

**Comment by annabauza** [comment]
@Amulya-coder no, we can just edit existing issue, cause at the moment it does not makes any sense.

**Review by annabauza — CHANGES_REQUESTED** [review]
Please adjust issue and pr to comments. Thanks!

**Comment by Amulya-coder** [comment]
@annabauza I have shared the screenshot just want to verify that it looks fine before pushed the new changes

image

**Comment by annabauza** [comment]
@Amulya-coder remove duplicated image please

**Pull request closed without merging**
