### PR TITLE
Added Hyperlinks in Ways to Contribute Section

### LINKED ISSUE #299: Add links to contribution section
### Is your feature request related to a problem? Please describe.
Noticed on the main page when you discuss the contribution guidelines, there are no links (like to the repo, commit message guidelines, etc.) I think it could use a couple!
image

### Describe the solution you'd like

Hyper link words like: 
- issues on Github (link to issue)
- issues labeled first timer only (link to issues with that tag)

### PR DESCRIPTION
**Pull request by anishfyi**
### Description

Added Relevant Hyperlinks In Ways To Contribute Section
- Text : "Creating issues on GitHub", Link : https://github.com/anitab-org/anitab-org.github.io/issues
- Text : "First Timers", Link : https://github.com/anitab-org/anitab-org.github.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22First+Timers+Only%22
- Text : "Commit Message Style Guide", Link : https://github.com/anitab-org/mentorship-android/wiki/Commit-Message-Style-Guide
- Q - Why Use HTML React Parser ?
- A - Initially The Content Was Text, So React Could Easily Parse Text and Convert it To Equivalent Text Nodes but in Case You Have Any HTML Content Coming Inside the Content, We Needed to Help React To Parse The Content to be Treated as Valid and HTML Tags Passed To Be Converted To React Nodes, We Needed HTMLReactParser Which Converts HTML Tags To Equivalent React Nodes.
We Had Two Options 1.) dangerouslysetInnerHtml 2.) Third Party Library HTMLReactParser.
I Chose to Use HTMLReactParser because dangerouslyInnerHtml has some security concern and react may discard it in future versions, Thereby Used HTMLReactParser

Fixes #299

- Hyperlinks Added
### Type of Change:
- Code

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

changes

### CODE REVIEW

**Comment by isabelcosta** [comment]
@daxoron I edited your PR description, to include `Fixes #299` because in this way it gets linked to your issue, and once this gets merged, that will get closed. This is also important, for me to see that you submitted a PR related to the correct issue. Please consider this for future PRs, it helps maintainers a lot 🤗

**Comment by isabelcosta** [comment]
@daxoron thank you for adding more context! Could you also fix the merge conflicts please 🙏🏾 I will request more reviews to get this approved :)

**Comment by daxoron** [comment]
@vj-codes @isabelcosta Merge Conflicts Resolved, Please Review and Merge.

**Comment by daxoron** [comment]
> @daxoron can you please check why the PR checks are failing? And hopefully, fix them 🤔

Yes, Checking Right Away 👍🏻

**Pull request merged**
