### PR TITLE
chore: update action to ensure we get the reference before running "prettier"

### PR DESCRIPTION
**Pull request by ftonato**
### Description

In order to fix the current problem we have with the action that is executed for "prettier", this PR forces that within the checkout action we always have the last reference (from current branch or pull-request).

### Type of Change:

- Chore (Process update)

### Issues

Fixes: #310

----
**References**

- https://github.com/anitab-org/anitab-org.github.io/pull/296#issuecomment-945129368

### CODE REVIEW

**Comment by isabelcosta** [comment]
cc @brittanyjoiner15 this PR looks relevant to your previous work :)

**Comment by isabelcosta** [comment]
@ftonato do you know why the check might be failing?

**Comment by isabelcosta** [comment]
@ftonato could you also create a ticket and link this PR to that issue. In this way, we have the issue documented and if for any reason you don't finish this, someone else can pick this up :)

**Comment by ftonato** [comment]
It's failing because "prettier" is trying to find any file regardless of file types (like .js or .json). I'll update the PR by adding the types that should be considered by the tool.

**Pull request merged**
