### PR TITLE
fix: About us style and code consistency, responsiveness.

### LINKED ISSUE #143: bug: About us is not displaying, code and style is inconstant with guide.
### Describe the bug
 About us is not displaying, code and style is inconstant with guide.

### To Reproduce
1. Go to About us on testing environment
2. See about us is not displayed

### Expected behavior
About us should display with expected code and styles consistency and following our guides.

### Screenshots
From testing page
Screenshot 2020-09-12 at 15 46 04
After adding existing about us code
Screenshot 2020-09-12 at 15 48 42
Expected
Screenshot 2020-09-12 at 15 44 17

### PR DESCRIPTION
**Pull request by annabauza**
### Description

Show about us and make sure consistency with styles and code are met. Please [test here](https://annabauza.github.io/anitab-org.github.io/)

Fixes #143

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
on deployed [testing GitHub page](https://annabauza.github.io/anitab-org.github.io/)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by rpattath** [comment]
@annabauza i had a quick look at the test page. Is the expectation that the "About us" page have to be shown as soon as I click the link and then inspect the styling consistency?

**Comment by annabauza** [comment]
@rpattath not sure what you mean. When you click about the web should show asap.

**Comment by annabauza** [comment]
@mtreacy002 @bismitaguha can you maybe review my code? Thanks!

**Comment by mtreacy002** [comment]
> @mtreacy002 @bismitaguha can you maybe review my code? Thanks!

Will work on it, @anna4j  👍

**Review by mtreacy002 — COMMENTED** [review]
@anna4j, below are my findings on issues related to responsiveness. Please check it out when you have time.

Screen Shot 2020-09-13 at 11 40 09 am
Screen Shot 2020-09-13 at 11 41 29 am

[Link to file](https://docs.google.com/document/d/1pHdIaTqdoWUKEPeQ_fHFEwGvM8Xl7yTxHePL5uBXJgQ/edit?usp=sharing)

**Comment by mtreacy002** [comment]
* An example of Navbar logo brand and About Us collided
Screen Shot 2020-09-13 at 12 04 37 pm

* An example of central image layout looks wrong/cut
Screen Shot 2020-09-13 at 12 05 59 pm

* An example of Feedback form layout looks wrong and cut
Screen Shot 2020-09-13 at 12 07 02 pm

* An example of Feedback form layout looks wrong but not cut
on iPad Pro landscape (I wasn't sure if this is actually the intended layout or not)
Screen Shot 2020-09-13 at 12 08 33 pm

on Pixel 2 XL landscape (looks like it slightly geared to the left)
Screen Shot 2020-09-13 at 12 10 07 pm

**Comment by annabauza** [comment]
Yeah we need to fix menu and footer as it breaks responsiveness @mtreacy002 @rpattath

**Comment by mtreacy002** [comment]
@annabauza, do we have specific design targets for different media screen for different page? Has the @anitab-org/design-team discuss the responsive design mockups? Just wondering.

**Comment by bismitaguha** [comment]
The navbar css needs media queries for specific screen widths<1000px @annabauza

**Comment by mtreacy002** [comment]
@bismitaguha , I don't think we need to use media queries in css. 
I'm totally new to react-native-reflect, but looking at their documentation, it seems like the framework uses unique ways to tackle responsiveness of UI (I had a quick look of their [docs](https://sntx.github.io/react-native-reflect/#/?id=description) and came across useStyled() hook, styled(View, { someTarget: [smaller screen, larger screen]  constants} as some of the view ways to define the responsiveness of the app. 

But regardless the methods being used, I think we still need to have set targets (mockup designs) on how we want the app to look on different devices. This will help when applying the type of methods and metrics to be used in our code as well as become the guidelines when we tests the UI features for responsiveness.

**Comment by mtreacy002** [comment]
I just came across the `breakpoints` that also looks like another way (or maybe used within, not sure, have to read more...) to define responsiveness

Screen Shot 2020-09-13 at 11 05 59 pm

**Comment by annabauza** [comment]
Fixing footer nad header should fix the rest. Let me prepare new test.

**Comment by annabauza** [comment]
@mtreacy002 @bismitaguha I confirm that issue is related to footer and navigation, which is not related to this PR. This is only about us section PR. Thanks!

**Comment by mtreacy002** [comment]
> @mtreacy002 @bismitaguha I confirm that issue is related to footer and navigation, which is not related to this PR. This is only about us section PR. Thanks!

@annabauza, I agree about the footer and navigation. How about the central image? will it be part of About Us page? I imagine that on mobile devices (or perhaps also smaller tablets) the top image would be placed on top of Content Text, am I right? Or is it common practice to have content as one default size for all devices and just use horizontal scrolling for the overflow? I'm new in design so want to learn more, can you give some pointers?

**Comment by annabauza** [comment]
@mtreacy002 it's because top nav is stretching the view.

**Comment by mtreacy002** [comment]
> @mtreacy002 it's because top nav is stretching the view.

I see.... Thanks, @annabauza for your explanation. So, I can approve this PR now since the bug is not related to the PR, correct?

**Comment by annabauza** [comment]
Yes

**Review by mtreacy002 — APPROVED** [review]
LGTM, @annabauza. Thanks for clearing out my doubt. 👍

**Pull request merged**
