### PR TITLE
feat: archive section added to projects page

### LINKED ISSUE #301: Add archive section to projects page
## Description
As a contributor,
I need to keep the website updated ,
so that the information is accurate and true.Thus add archive section to the page to display archived projects like mentorship-ios and flutter, vms and portal OR remove them from projects page

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by abritpal**
### Description

Added an archived section to the projects page.

Fixes #301

### Type of Change:

**Delete irrelevant options.**

- Code: In `anitab-org.github.io\src\content\projects_content.js` added a new objects with title `Archives` to the `sections` list
- User Interface: new section added to the projects page

**Code/Quality Assurance Only**

### How Has This Been Tested?
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
Thank you so much for your contribution @abritpal :)
LGTM 🎉

**Review by isabelcosta — APPROVED** [review]
Great work @abritpal 🙌🏾 Thank you for contributing!

**Comment by abritpal** [comment]
Thanks for letting me Contribute!

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Ran project locally and ran this locally_  
     _Screenshot/gif_:  
    archived projects section

     _Expected Result_:  Archived projects show under active projects
     _Actual Result_: As expected 🎉 

3. Status of PR Changed to: Ready to Merge.

**Pull request merged**
