### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sakshi-vats**
### Description

Fixes broken link for CONTRIBUTING.md in the current README.md (screenshot attached)

Screenshot 2021-11-09 at 6 20 14 PM

### Type of Change:

- Documentation

### How Has This Been Tested?
Screen_Recording_2021-11-09_at_6_26_12_PM_SparkVideo

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by isabelcosta** [comment]
@sakshi-vats can you create an issue that will be linked to this PR :) your changes are good. It's just as part of our contribution guidelines, that you work on tasks you are assigned to.

**Comment by sakshi-vats** [comment]
@isabelcosta I have created [this](https://github.com/anitab-org/anitab-org.github.io/issues/336#issue-1059453527) issue for the PR. You can assign me there?

**Review by isabelcosta — APPROVED** [review]
Thank you for creating the issue and fixing this 🙌🏾 @sakshi-vats !

**Review by gaurivn — APPROVED** [review]
LGTM, Thank you

**Comment by sakshi-vats** [comment]
Thanks for approving this! @isabelcosta @gaurivn

**Pull request merged**
