### PR TITLE
fix: Documentation needs text formatting for better readability

### LINKED ISSUE #192: Documentation needs text formatting for better readability
### Describe the bug
There is a need for line break in between subtopic heading and points. This should be done on the home webpage.

### To Reproduce

Line breaks are needed at several places

1.
Now :
image 1

After:
image 4

2.
Now:
image 2

After:
image 5

3.
Now:
image 3

After:
image 6

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser : Chrome
    Version : Latest

### PR DESCRIPTION
**Pull request by Amulya-coder**
### Description

Provided the line breaks wherever required for better readability. 

Fixes #192 

### Type of Change:
- Documentation

### How Has This Been Tested?
image
image
image
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Amulya-coder** [comment]
@nandini45  As there was the confusion associated with whose pr is taken into account for this issue so that's why I had not created a pr.

**Comment by Amulya-coder** [comment]
@nandini45 now you can review it.

**Comment by Rahulm2310** [comment]
@nandini45 Can we bolden the heading a little to emphasize them?

**Comment by Amulya-coder** [comment]
> @Amulya-coder These new lines are not increasing readability. @nandini45 Can we bolden the headings a little to emphasize them?

@Rahulm2310, you mean the sub-headings?

**Review by jhalak27 — COMMENTED** [review]
It is still not much readable and could look better. If possible could you add some formatting in the subheadings to make them different from their content, such as increasing size or make them bold?

**Review by isabelcosta — APPROVED** [review]
Thank you for contributing @Amulya-coder 🙌🏾 
I think you accomplished what the issue asked 💯

**Review by gaurivn — APPROVED** [review]
Looks good to me :+1: :

**Pull request merged**
