### PR TITLE
Tech talk component in the events page

### LINKED ISSUE #122: coding: develop the tech talk section in events page
## Description
As a developer, I need to see all the videos of the talks held by the community regarding open source and anitab-org , so that the user can know more about us and what we do.

## Mocks
image

the spacing is 16 from both sides

### Update [Required]
- [ ]  Follows all the design guidelines as mentioned and is responsive enough on large screen devices.
- [ ]  the talk should be as mentioned in the doc

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by imrishabh18**
### Description

I have made the carousel with proper props and state. Some styling is still left as I was not getting the proper colors. Will be helpful if you can send me those as well as the video links. For the time being, I have used a random photo.

Fixes #122

### Type of Change:

- Code
- User Interface

### Checklist:

- [✅ ] My PR follows the style guidelines of this project
- [ ✅] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by imrishabh18** [comment]
Hey @nandini45 , review this PR please 😃

**Comment by nandini45** [comment]
@imrishabh18  can you recheck your travis check it is failing?

**Comment by imrishabh18** [comment]
@nandini45 I am not able to resolve why this travis build check fails. Can you help me with this?

**Comment by nandini45** [comment]
yeah sure @imrishabh18 
can you tell me where did you get the image you used?

**Comment by imrishabh18** [comment]
It is link from unsplash

**Comment by nandini45** [comment]
i dont think we can do. did you check the repository ?
 was there any image which you can use?

**Pull request closed without merging**
