### PR TITLE
 resolve issue #108

### PR DESCRIPTION
**Pull request by Malvika18**
Content: Create introduction to AnitaB.org Open Source section for home page #108

### CODE REVIEW

**Comment by nandini45** [comment]
@Malvika18  thanks for the contribution but can you please edit the pull request template

**Comment by Malvika18** [comment]
Mam can you please guide me regarding this  because i am a beginner and
this is my first PR

**Comment by nandini45** [comment]
@Malvika18  no maam please
 https://github.com/anitab-org/anitab-org.github.io/pull/86
 look at this issue description you will know to changes the PR template..

**Comment by siddhipandare** [comment]
Hi, @Malvika18 do you still need help? I think you deleted the forked repo. 
@nandini45 Can Malvika still work on this? I'll try to help her as much as possible.

**Comment by Malvika18** [comment]
> Hi, @Malvika18 do you still need help? I think you deleted the forked repo.
> @nandini45 Can Malvika still work on this? I'll try to help as much as possible.

**Pull request closed without merging**
