### PR TITLE
Feat: added snapshot test for components

### LINKED ISSUE #23: Add jest tests and snapshots
## Description
As a Developer,
I need to add jest test and snapshots,
so that I can see automated tests has passed on PR.

### Update [Required]
- [ ] contain at least 1 test and at least 1 snapshot

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by Bucky25**
### Description

Snapshot test for each component using jest .

Fixes #23 

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
its does cannot be checked with hosted website on github.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Bucky25** [comment]
@annabauza @isabelcosta  please tell me if another test are to be included.

**Comment by annabauza** [comment]
@Bucky25 did you add all dependencies in project.json?

**Comment by Bucky25** [comment]
> @Bucky25 did you add all dependencies in project.json?

what are those dependencies.

**Comment by annabauza** [comment]
https://testing-library.com/docs/react-testing-library/intro

**Comment by Bucky25** [comment]
@annabauza do i have to add any other test other than snapshot for each element .

**Comment by Bucky25** [comment]
@annabauza please review it .

**Review by annabauza — APPROVED** [review]

**Pull request merged**
