### PR TITLE
feat: add programs and projects information to programs page

### LINKED ISSUE #308: Programs information in text format
## Description

As a newcomer to the community,
I need information about programs and project community has participated,
so that I can learn more about the community.

Throughout the years, we have been participating in multiple Open Source programs.
- https://systers.io/gsoc/2017.html
- https://systers.io/gsoc/2016.html
- https://systers.io/gsoc/2015.html

Until we have a more interactive way of showing our participation in open source programs, having text-based information should be enough.

You can take a look at https://systers.io/#programs and ask for more information if you need it. We also participated in GCI 2019, GSoC 2018, and GSoC 2020. For GSoC we could even use the link for archives in GSoC to provide more information. https://summerofcode.withgoogle.com/

Feel free to start simple, we can always improve over time :)

## Mocks

There are no mocks available yet. I would suggest playing with a simple bullet-pointed structure.

### Update [Required]

- [ ] Add information to Programs page about at least, GSoC 2018, GCI 2019 and GSoC 2020
- [ ] (optional) Add information about previous GSoC programs

## Definition of Done

- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by WizardLemon**
### Description

Currently working on adding a table component for displaying this data.
The idea is to have a section component that will hold the data and possibly be collapsible, and a child table component that will display the data. I want the table to be as flexible as possible, so that it could potentially be used for other things as well.

Relevant links:
https://summerofcode.withgoogle.com/archive/2020/organizations/5270382996619264/
https://codein.withgoogle.com/archive/2019/organization/5698265715048448/
https://summerofcode.withgoogle.com/archive/2018/organizations/6321870005600256/
https://summerofcode.withgoogle.com/archive/2017/organizations/5429781541683200/

https://systers.io/gsoc/2017.html
https://systers.io/gsoc/2016.html
https://systers.io/gsoc/2015.html

https://systers.io/#programs

Fixes #308

### Type of Change:

- Code
- User Interface
- Outreach
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
The changes generate no warnings or errors, and the site has been deployed to 
https://wizardlemon.github.io/anitab-org.github.io/
The changes are under the programs tab.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have attached link of deployed site.
- [x] Any dependent changes have been merged
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vj-codes** [comment]
@WizardLemon hey thank you so much for the PR! 
About the colors, there's a brand guide and will inform you the hex codes as per it. 
And for Google Code In, there's basically 4 finalists and 2 grand prize winners. So the format may include 2 columns for finalists and winners, also you can add the projects participating during GCI in one row at top probably. 
What say?

**Comment by vj-codes** [comment]
@isabelcosta does open source hack count one of the programs? 👀

**Comment by WizardLemon** [comment]
> 
> 
> @WizardLemon hey thank you so much for the PR! About the colors, there's a brand guide and will inform you the hex codes as per it. And for Google Code In, there's basically 4 finalists and 2 grand prize winners. So the format may include 2 columns for finalists and winners, also you can add the projects participating during GCI in one row at top probably. What say?

@vj-codes thanks for the reply, I'm having trouble finding the brand guide, I've searched in the repo and the organization, can you provide a link for the brand guide so I can update the table?

For GCI I think I've found the information you were talking about, thanks for the suggestion! 😀

**Comment by vj-codes** [comment]
@WizardLemon the brand guide is not public I guess, I'll probably attach a screenshot of the color codes in a few minutes

**Comment by WizardLemon** [comment]
This is how I went with GCI 2019, how does it look?

image

**Comment by vj-codes** [comment]
@WizardLemon looks awesome!!! 💯 
btw since we are adding all gsoc program years, how about adding all GCI years info as well? The issue states only 2019 but systers was participating in 2014-2017 every year, if it is too much work for you do let us know and we can create a separate ticket :)

here's the brand guide ss -
Don't use too contrast colours
Screenshot 2021-10-30 at 9 18 08 PM

Screenshot 2021-10-30 at 9 31 24 PM

**Comment by WizardLemon** [comment]
@vj-codes it's not a problem adding the data, it might just take me a bit longer to find and put all the data in

thanks for the help, I went with Navy and Carribean, it does look a lot nicer now 😁

image

**Comment by vj-codes** [comment]
@WizardLemon it does look better 🚀 
Here's the links for previous contests-
https://codein.withgoogle.com/archive/2017/
https://codein.withgoogle.com/archive/2016/
https://codein.withgoogle.com/archive/2015/

**Review by isabelcosta — COMMENTED** [review]
This is looking great! Thank you for working on this 👏🏾 
I don't think this PR has to have all the additions of the programs. If you wish to leave some for another issue, this is already looking great.

I think the color palette change suggestion that @vj-codes made was super helpful to make this even better.

**Comment by WizardLemon** [comment]
@isabelcosta adding the Google Code-in's wouldn't be much work, but I think it would make a good `first timers issue` for the repository 😁

I'll update my GitHub pages deployment of the website, so the updated version can visually reviewed more easily.

**Review by isabelcosta — APPROVED** [review]
Looks good to me! Thank you @WizardLemon for starting this piece of work 🙌🏾

**Comment by isabelcosta** [comment]
> @isabelcosta adding the Google Code-in's wouldn't be much work, but I think it would make a good `first timers issue` for the repository 😁
> 
> I'll update my GitHub pages deployment of the website, so the updated version can visually reviewed more easily.

cc @vj-codes what do you think? I approved, we can then create a follow up

**Comment by vj-codes** [comment]
@isabelcosta yes definitely it can be a new first timers only issue :)

**Comment by vj-codes** [comment]
@isabelcosta btw the name for anitab forms is as open source programs as per the data on the official site, should we add a bracket and mention now called anitab forms? There's a high chance someone going through the list and looking for the repos on our GitHub and will have problem with it. 
What say? Other than this I am ready to approve :/

**Comment by isabelcosta** [comment]
@vj-codes yes we can do that :) I am also imagining for a next issue, making those projects link to the projects on gsoc official website 🤔 

@WizardLemon can you do what Vaishnavi mentioned. It's just putting next to "Open Source Programs" putting "Open Source Programs (AnitaB Forms)"

**Comment by isabelcosta** [comment]
And thank you a lot for making this available on your GitHub pages @WizardLemon ! that helps soooo much 🙌🏾 
Was it any difficult, I am tempted to create an issue and ask for future contributors to try to do this, because it really helps maintainers not spend time checkout the branch themselves

**Comment by WizardLemon** [comment]
> 
> @WizardLemon can you do what Vaishnavi mentioned. It's just putting next to "Open Source Programs" putting "Open Source Programs (AnitaB Forms)"

Updated 🚀


>And thank you a lot for making this available on your GitHub pages @WizardLemon ! that helps soooo much 🙌🏾
>Was it any difficult, I am tempted to create an issue and ask for future contributors to try to do this, because it really helps >maintainers not spend time checkout the branch themselves

It wasn't difficult, I just followed the testing guidelines here https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR
Maybe the process could be streamlined somehow, but I'm not sure, I can look into it and if I find a solution I will create an issue for this with a suggested solution :)

**Review by isabelcosta — APPROVED** [review]
Thank you for updating this 👍🏾 cc @vj-codes

**Review by vj-codes — APPROVED** [review]
Thank you soo much @WizardLemon for your contribution, especially deploying the site on your account and making quick changes throughout🎉
I tested your deployment on web as well as mobile, works as expected and it's responsive too, great work 💯 🙌

**Comment by isabelcosta** [comment]
@vj-codes can you please create an issue about the additional work for GCI. I didn't fully grasp the work that was left.

I will create an issue to make the project linkable redirecting to the project on GSoC official website

**Comment by vj-codes** [comment]
@isabelcosta yeah I'll do that tomorrow!

**Pull request merged**
