### PR TITLE
Testing: Deployed anitab-org.github.io on netlify

### LINKED ISSUE #106: Deploy a development version of the app to Heroku
## Description
As a contributor,
I need to have a development deployed version of the app,
so that I can test the app before releasing a production version.

We want to have this available from a URL on Heroku.

### Update [Required]
- [ ] Make this deployable on Heroku

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
🤷‍♀️ hours

### PR DESCRIPTION
**Pull request by saideepesh000**
### Description

Changes some files to deploy the site on netlify.

Fixes #106 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by isabelcosta** [comment]
@saideepesh000 can you include more of the template, such as the checklist: https://github.com/anitab-org/anitab-org.github.io/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

Can you also give the details of how you deployed to netlify? Or was it very straightforward?

**Comment by nandini45** [comment]
@saideepesh000  netlify is a paid for teams right?
and if i am wrong tell me what i am missing
image

**Comment by isabelcosta** [comment]
Personal use is fine, at Heroku I am using a personal account @nandini45 
I think Heroku would also be paid for teams. Heroku would be preferred, just so we could restrict ourselves to apps we already use such as Heroku.

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 netlify is a paid for teams right?
> and if i am wrong tell me what i am missing
> image

Ya I think it's not free, [netlify](https://www.netlify.com/pricing/)

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 can you include more of the template, such as the checklist: https://github.com/anitab-org/anitab-org.github.io/blob/develop/.github/PULL_REQUEST_TEMPLATE.md
> 
> Can you also give the details of how you deployed to netlify? Or was it very straightforward?

I deployed the site using Github, just authorize the GitHub account with netlify, select a repo, and deploy it.

**Comment by annabauza** [comment]
@saideepesh000 checklist should not be modified just tick the one you have done.

**Comment by saideepesh000** [comment]
@annabauza, Actually this is not meant to be merged, @isabelcosta, want's to deploy the site but on Heroku it didn't work and while trying with netifly, I managed to change these warnings and it worked, so she asked me to PR what were the changes made.

**Comment by annabauza** [comment]
Regardless checklist should not be modified.

**Comment by saideepesh000** [comment]
> 
> 
> Regardless checklist should not be modified.

@annabauza, should I close this PR, because I am not able open a new PR with the same changes

**Comment by nandini45** [comment]
@saideepesh000  instead of doing that i think you can edit this PR . 
remove the changes you created in the project_content.js
and update this PR 
and after that you can create a new PR  for the issue 117

**Comment by saideepesh000** [comment]
@nandini45 , I didn't get you, I'll close this PR and create a new PR instead.

**Comment by nandini45** [comment]
ok

**Comment by annabauza** [comment]
@isabelcosta do we still need this PR?

**Comment by isabelcosta** [comment]
@annabauza I don't think so :) I created this solely as a temporary solution for the test `develop` code. Now that we have the test path we don't need this.

**Pull request closed without merging**
