### PR TITLE
updated key props

### LINKED ISSUE #215: Missing Key Props ISSUE
### Missing key props
key props are not implemented in map method in components

### To Reproduce

- start the app 
- press cntrl + shift + I to open console
- there are warnings due to missing key props or not having a unique key

warnings
###components that don't have unique key props or dont have a key are :

1. ContributionSection
2. ContributionCard
3. Home
4. Projects
5. Events
6. Contribute

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser :Chrome
 - Version 88.0.4324.104

### PR DESCRIPTION
**Pull request by atharmohammad**
### Description

map method in some components didn't had the key props.

Fixes #215 

Added key props in components :

1. ContributionSection
2. ContributionCard
3. Home
4. Projects
5. Events
6. Contribute

### Checklist:
**Delete irrelevant options.**

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@atharmohammad I suggest when contributing to a open source project, please wait for a maintainer to assign you the issue before creating a pull request. I think the maintainers also respect the fact that we all are excited to contribute to open source but be patient. Please have a look at the [contributing guidelines](https://github.com/anitab-org/anitab-org.github.io/blob/develop/CONTRIBUTING.md) of the project. Thanks 🙂

**Comment by atharmohammad** [comment]
> @atharmohammad I suggest when contributing to a open source project, please wait for a maintainer to assign you the issue before creating a pull request. I think the maintainers also respect the fact that we all are excited to contribute to open source but be patient. Please have a look at the [contributing guidelines](https://github.com/anitab-org/anitab-org.github.io/blob/develop/CONTRIBUTING.md) of the project. Thanks 🙂

thank you , will keep this in mind from next time

**Review by annabauza — CHANGES_REQUESTED** [review]
Thank you @atharmohammad but this issue was not approved and moreover not assigned to you. Please read contribution guideline first. Thank you.

**Comment by atharmohammad** [comment]
> Thank you @atharmohammad but this issue was not approved and moreover not assigned to you. Please read contribution guideline first. Thank you.

Thank you, I recently started open source will keep this in mind in future

**Review by annabauza — APPROVED** [review]
💯

**Pull request merged**
