### PR TITLE
fixing typo in the archive page under Projects

### LINKED ISSUE #355: Typo in Archive page
### Describe the bug

There is a typo in the description of archived projects

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on Projects
3. Scroll down to "Archived Projects" section
4. See description of section with typo in word "avialable"

### Expected behavior

Should have "available" instead of "available"

### Screenshots

typo in archived projects section

### Additional context

This applies to any device where this website can be accessed.

### PR DESCRIPTION
**Pull request by Esther-Wavinya**
### Description
Fixes #355 

## Type of Change:
Code

### Code quality Assurance
Bug fix (non-breaking change which fixes an issue)
My PR follows the style guidelines of this project
 I have performed a self-review of my own code or materials
 
### Code/Quality Assurance Only
 My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
The change looks good :) Thank you for contributing!
Could you add more context to the PR description, even if some don't apply to the change, you can leave the items unchecked. Here's the template: https://github.com/anitab-org/anitab-org.github.io/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

**Review by vj-codes — APPROVED** [review]
Congrats on your first PR to the repository @Esther-Wavinya  🎉 
LGTM!

**Comment by vj-codes** [comment]
@isabelcosta how do you deploy a PR and test it?

**Comment by isabelcosta** [comment]
@vj-codes I think from the README, that once on `develop`, we can merge from `develop` to `production` and it would work.

Excerpt from README:
excerpt from README that mentions 3 branches that are important

**Review by isabelcosta — COMMENTED** [review]
@Esther-Wavinya would you be able to run this on your code
```
yarn test -u
```

this is supposed to update the test snapshots, which is [failing](https://github.com/anitab-org/anitab-org.github.io/runs/6837703790?check_suite_focus=true) in the CI/CD pipeline ran by GitHub Actions

**Comment by Esther-Wavinya** [comment]
Should I just run that?

**Comment by isabelcosta** [comment]
> Should I just run that?

yes :)

**Comment by isabelcosta** [comment]
> Should I just run that?

@Esther-Wavinya did you have the chance to do this?

**Comment by Esther-Wavinya** [comment]
> > Should I just run that?
> 
> @Esther-Wavinya did you have the chance to do this?

Yes

**Comment by Esther-Wavinya** [comment]
@isabelcosta & @vj-codes I think this PR should be closed.

**Review by vj-codes — APPROVED** [review]
Thank you for your contribution @Esther-Wavinya !

**Pull request merged**
