### PR TITLE
test: Add jest tests and snapshots

### LINKED ISSUE #23: Add jest tests and snapshots
## Description
As a Developer,
I need to add jest test and snapshots,
so that I can see automated tests has passed on PR.

### Update [Required]
- [ ] contain at least 1 test and at least 1 snapshot

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by gaurivn**
### Description
Add jest tests and snapshots.

Fixes #23 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
`yarn test App.test.js`

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by gaurivn** [comment]
@annabauza  I am not getting the snapshots correctly. Would be very grateful if you could help me sort this out.

**Comment by annabauza** [comment]
sure @gaurivn will do later on today!

**Comment by annabauza** [comment]
@gaurivn try to follow this https://jestjs.io/docs/en/tutorial-react-native

**Comment by annabauza** [comment]
and call `yarn test -u`

**Comment by gaurivn** [comment]
Thank you @annabauza , I will refer the link you sent and do accordingly.

**Comment by gaurivn** [comment]
@annabauza , I was facing merge conflicts so I ended up making few commits to restore the original files, I will work on this issue later today and commit here.

**Comment by annabauza** [comment]
ok so it seems you took changes from master instead of develop

**Comment by annabauza** [comment]
this might help you `git fetch upstream && git pull upstream develop`

**Comment by gaurivn** [comment]
I remember, I did that, I took changes from master by mistake, and then I did with develop. And all the while there were few merge conflicts in this branch, patch_four, that got solved in few commits. Then I undid the changes I made, deleted those static files.

**Comment by gaurivn** [comment]
@annabauza ,thank you, I had done the same way, and all the conflicts had got solved.

**Pull request closed without merging**
