### PR TITLE
Add Linking to import from 'react-native'

### LINKED ISSUE #280: Linking component is not being imported, which is currently breaking build (:
## Description

So there is a little error in one of the files that is causing fail in the build. I merged the PR very recently 🤦🏾‍♀️  https://github.com/anitab-org/anitab-org.github.io/pull/247

Error 😳  https://github.com/anitab-org/anitab-org.github.io/runs/3175046196
```
./src/Components/Footer/Social.js
  Line 52:13:  'Linking' is not defined  no-undef
```
### Update [Required]
- [ ] Fix error that is breaking build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by mimzivvimzi**
### Description

Just adding the "import Linking" at the top of ./src/Components/Footer/Social.js 😊 

Fixes #280

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

### Checklist:
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Nice @mimzivvimzi ! thank you for contributing!

Could you just edit the PR description to remove the irrelevant bits and show how you tested this change :) it will make this PR nicer to review.

**Review by vj-codes — APPROVED** [review]
@mimzivvimzi congrats on your first contribution to the repository 🎉
LGTM! 
Quick tip : checkout to a new branch, other than develop branch of your fork and then commit the changes in the future as mentioned in the community guidelines :)

**Comment by mimzivvimzi** [comment]
> @mimzivvimzi congrats on your first contribution to the repository 🎉
> LGTM!
> Quick tip : checkout to a new branch, other than develop branch of your fork and then commit the changes in the future as mentioned in the community guidelines :)

Ah, I see-- got it! :)

**Review by isabelcosta — COMMENTED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Start the web server locally_  
     _Screenshot/gif_:  
    website working on localhost

     _Expected Result_:  the app loads successfully
     _Actual Result_: app loaded successfully
  
3. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
Thank you for contributing @mimzivvimzi 👏🏾 🙌🏾

**Pull request merged**
