### PR TITLE
docs: changed program name to match the title

### LINKED ISSUE #190: Same description in Google Summer of Code and Google Code in Section
### Describe the bug
The introductory description under Google Summer of Code and Google Code-in is the same, even the name of the event has not been changed.

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Scroll down to **Open Source Programs**
3. See error

### Expected behavior
Different description of different programs

### Screenshots
image

### PR DESCRIPTION
**Pull request by jalajcodes**
### Description

Changed program name to `Google Code In`

Fixes #190 

### Type of Change:

- Documentation

### How Has This Been Tested?
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Comment by jalajcodes** [comment]
Someone please review and merge it.

**Comment by devkapilbansal** [comment]
@jalajcodes consider asking it to zulip in appropriate channel

**Review by vj-codes — CHANGES_REQUESTED** [review]
@jalajcodes hey can you also add the year 2020 under Google Summer of Code ?
This is a small change and creating a different issue won't make much sense and since you are updating the same file it'll be done faster :)

**Comment by jalajcodes** [comment]
@vj-codes done. 😃

**Review by nandini45 — APPROVED** [review]
@jalajcodes the changes are good to go
I will merge it.
Thanks for thr work

**Comment by nandini45** [comment]
@vj-codes  can u approve the changes. And merge it

**Review by vj-codes — APPROVED** [review]
@jalajcodes LGTM 🎉

**Comment by vj-codes** [comment]
@nandini45 I don't think I have the merge access 👀

**Review by annabauza — APPROVED** [review]
Would be great to move \n to new paragraphs but maybe we can rise it as new issue to review other content files.

**Pull request merged**
