### PR TITLE
Deleted ISSUE_TEMPLATE from the repository issue#242

### LINKED ISSUE #242: Delete .github/ISSUE_TEMPLATE folder
## Description
As a org contributor,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on [https://github.com/anitab-org/.github](https://github.com/anitab-org/.github), we don't need to have issue templates present in the repository. Read more about these type of files here [https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)

### Update [Required]
- [ ] [Delete .github/ISSUE_TEMPLATE]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Ayush0730**
### Description

Deleted .github/ISSUE_TEMPLATE folder and modified files where it was referenced

Fixes #242 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**

- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
Congrats on your first contribution to the repository @Ayush0730 🎉

**Comment by vj-codes** [comment]
Adding label ready to merge since no code has been changed

**Comment by isabelcosta** [comment]
@Ayush0730 could you please resolve the conflicts in the PR? After that, I can merge this PR.

**Comment by Ayush0730** [comment]
Please check and inform me if I have done something wrong...

**Comment by Ayush0730** [comment]
> @Ayush0730 could you please resolve the conflicts in the PR? After that, I can merge this PR.

Done. Please let me know, if I have done something wrong

**Comment by vj-codes** [comment]
@Ayush0730 resolved successfully 💯

**Pull request merged**
