### PR TITLE
Project Section

### LINKED ISSUE #81: CODING: Develop the projects section on projects section
### Description
As a developer,
I need the following section of mockup to be developed,
so that I can add it in my projects page :  https://xd.adobe.com/view/e86737c2-ff84-4e23-b4b1-e541508d5279-bd34/

### mocks

spacing and all details

image

image

image

{font style-avenir color style-#103B81 Weight-medium}
### Acceptance Criteria

- [x] Follows all the design guidelines as mentioned and is responsive enough on large screen devices.
- [x] when clicked on ( view more ) all the listed projects should up .
- [x] the github and zulip redirect links should work in all  cards .

### Definition of Done

- [x]  All of the required items are completed.
- [x]  Approval by 2 mentor.

### Estimation
6 -7 hours

HAPPY CODING !! 😃

### PR DESCRIPTION
**Pull request by happycoder0011**
### Description

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #81 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by happycoder0011** [comment]
> This is not react native. please create react native PR.

can't we use material UI

**Comment by annabauza** [comment]
@happycoder0011 I linked one you can use in preview PR you have closed.

**Comment by annabauza** [comment]
happycoder0011  ideally you could make it in a way we did sponsors. This would keep consistency in a app. Thanks!

**Comment by nandini45** [comment]
@happycoder0011  are u working on it?

**Comment by happycoder0011** [comment]
No

**Comment by nandini45** [comment]
@happycoder0011  can you tell where you left off? and what will the next contributor working on it will do?

**Comment by annabauza** [comment]
Closing this PR due contributor is not available. I will take over this task.

**Pull request closed without merging**
