### PR TITLE
Added relative paths to files located within the repository's README file.

### LINKED ISSUE #29: Add relative paths to files located within the repository
## Description
As a contributor,
I need see relative paths to repository files on the README,
so that I can see them properly on my fork README rendering.

On README the links to LICENSE, CONTRIBUTING.md, etc located within the repo, have absolute links to this organization repo, this causes to within our forks, it is linked to these files in the `anitab-org` organization files instead of on my fork's files.

### Update [Required]
- [ ] Turn paths to local files from absolute paths to relative paths on README

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by garimasingh128**
### Description

Add relative paths to files located within the repository.

Fixes #29 

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by garimasingh128** [comment]
> I would suggest to not make PRs from develop. Apart from that everything looks good.

How do I now change my branch without creating another PR?

**Comment by gaurivn** [comment]
Check [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request).

**Comment by gaurivn** [comment]
I am not sure about that. It would be better if you could create a new pull request from a different branch. @isabelcosta , grateful if you could help.

**Comment by garimasingh128** [comment]
@gaurivn  I closed the above PR and created a new one. Kindly check.

**Comment by gaurivn** [comment]
Sure, will do.

**Pull request closed without merging**
