### PR TITLE
Deleted .github/ISSUE_TEMPLATE folder and updated the links.

### LINKED ISSUE #242: Delete .github/ISSUE_TEMPLATE folder
## Description
As a org contributor,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on [https://github.com/anitab-org/.github](https://github.com/anitab-org/.github), we don't need to have issue templates present in the repository. Read more about these type of files here [https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)

### Update [Required]
- [ ] [Delete .github/ISSUE_TEMPLATE]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by im-sakshijain**
### Description

Deleted .github/ISSUE_TEMPLATE folder. Also, I've updated the links to this file wherever it is required. 

Fixes #242 

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Amulya-coder — APPROVED** [review]
LGTM!! @im-sakshijain 🎉

**Review by shades-7 — APPROVED** [review]
Everything seems good. well done @im-sakshijain :+1:

**Comment by HeroicHitesh** [comment]
LGTM. Nice work @im-sakshijain 🎉

**Comment by Rahulm2310** [comment]
@keshakaneria Please add `Ready to Merge` label as it already has 3 approvals.

**Comment by annabauza** [comment]
@im-sakshijain can you resolve conflicts please?

**Comment by isabelcosta** [comment]
Thank you for your work @im-sakshijain I will close and make the PR available again due to lack of update.

**Pull request closed without merging**
