### PR TITLE
Coding: Meet Our Open Source Community Part Of About Page 

### LINKED ISSUE #53: Coding: Design The Meet Our Open Source Community Part Of About Page
## Description
As a developer,
I need the following mock-up to be implemented,
so that I can add as Open-Source Community Component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks
(Only the section in the red box to be developed)
about-us-part2

Font Size for heading MEET OUR OPEN SOURCE COMMUNITY: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81

Margin between heading and description: 16pt
Image size: 81px X 81px
horizontal and vertical gutter between two images: 2px 
corner radius: 8px
Top margin of the entire image component on page: 1320px
image block size: height:310px ,width:1638px

[Design Development Link](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/)

### Update [Required]
- [ ] Instead of dummy images in MEET OUR OPEN SOURCE COMMUNITY, get GitHub profile images of all members and arrange them according to mock-up shared, also when a user hovers on a particular image redirect them to respective Github profiles.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### LINKED ISSUE #89: Content- Add a description for Events Section
## Description
As a developer,
I need a welcoming and friendly description for Events,
so that I can replace the default text field in the mock.

## Mocks
events-content

### Update [Required]
- [ ] The description should be brief yet engaging and should encourage the users to explore our events and participate in them

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-8 hours

### LINKED ISSUE #90: Coding: Develop the following Events Section
## Description
As a developer,
I need the following section to be developed,
so that I can add it as an Events component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks
Develop the section in the red box only
event1

Font Size for heading EVENTS: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81

[Design Link for Development](https://xd.adobe.com/view/237a598d-ce4a-4fee-5642-3048a38e6a8b-554b/)

### Update [Required]
- [ ] Should follow all the margin guidelines mentioned above and should be responsive

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-8 hours

### PR DESCRIPTION
**Pull request by anna4j**
### Description

Developed the **Meet Our Open Source Community** Part Of About Page 
Currently, the it features only four users whom I've repeated to showcase the grid. The reason for that is that the list of members isn't concrete as of now. 
No additional dependencies required. The additional dependencies visible in package.json are required for a different issue, not this one.
Changes can be viewed [here](https://drive.google.com/file/d/1qHVAMMSyXLofsbLjEwwRWh4dpfgPJ-Zd/view?usp=sharing)
Fixes #53 

Developed the **Events** Part Of Events Page and wrote corresponding content
The responsiveness of the component needs some work. Other than that I've attached a picture below. I'll attach a gif of responsiveness also soon.
No additional dependencies required. 
Untitled
Fixes #89  
Fixes #90 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
The feature added is responsive in nature. Each profile picture navigates to the member's GitHub profile.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by anna4j** [comment]
@Sonal240 I've basically added the hosted the "Meet our open source community" section in the App.js for the time being as the AboutUs.js file isn't created. Later on, this component can be hosted on the AboutUs page when it's created. Thank you I'm glad it looks good. 
I've opened a new pull request with the JSON file. The component functions same as before so not attaching a gif.

**Comment by Sonal240** [comment]
We just want it as a component... So you may remove it from App.js file... Regarding the JSON file I'll see and revert back to you thanks

**Comment by Sonal240** [comment]
Hey, @anna4j have you updated the gif as well after committing all the changes?

**Comment by anna4j** [comment]
@Sonal240 okay, I'll remove it. Yes gif is updated

**Pull request closed without merging**
