### PR TITLE
medium link is added to footer

### PR DESCRIPTION
**Pull request by shades-7**
### Description

Added medium link and icon in the footer.
Fixes # 226

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

https://user-images.githubusercontent.com/58786336/108236021-751a5a00-716c-11eb-9fef-651dabb067b1.mp4

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by shades-7** [comment]
@nandini45 can you please review this pull request?

**Comment by Rahulm2310** [comment]
@shades-7 Please go through the [Contribution Guidelines](https://github.com/anitab-org/anitab-org.github.io/blob/develop/docs/CONTRIBUTING.md). Update the PR description and remove irrelevant options. Also, add issue number your PR is fixing. Thanks 🙂

**Comment by shades-7** [comment]
@Rahulm2310 Okay will let you know the update soon. Thanks for the guidance

**Comment by nandini45** [comment]
@shades-7 i agree with rahul 
. after doing the changes i will review it further.
thanks

**Comment by shades-7** [comment]
@Rahulm2310 Hey, i have updated the PR description. Please let me know if any future updates require.

**Review by Rahulm2310 — COMMENTED** [review]
Good Job @shades-7 🎉 . Thanks for your contribution.

**Comment by shades-7** [comment]
> @shades-7 i agree with rahul
> . after doing the changes i will review it further.
> thanks

@nandini45 please review it, I have made the changes

**Comment by Rahulm2310** [comment]
@shades-7 Try not to use `develop` branch for submitting a PR. Please create a seperate branch for submitting a PR. Please go through the [Contribution Guidelines](https://github.com/anitab-org/anitab org.github.io/blob/develop/docs/CONTRIBUTING.md). It would be great if you can close this PR and submit a PR from a seperate branch (not develop). Thanks 🙂 

Cc: @nandini45 @annabauza

**Pull request closed without merging**
