### PR TITLE
Grammatical error fixes

### LINKED ISSUE #203: Grammatical Errors
### Describe the bug
There are a few grammatical errors in the `home` , `Projects`  and `About Us` page description.

### To Reproduce
1. Go to https://anitab-org.github.io
3. See errors in the descriptions

### Expected behavior
All the grammatical errors needs to be fixed.

### Screenshots
Home Page
osp-grammar1
osp-grammar2
osp-grammar3

Projects
osp-grammar4

About Us
osp-grammar5

Events
grmtical-issue

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome 
 - Version : 84

### PR DESCRIPTION
**Pull request by Rahulm2310**
### Description

This PR fixes some grammatical errors from different pages.

Fixes #203 

### Type of Change:
**Delete irrelevant options.**
- Coding

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Screenshots of the bug fixes
Home Page
home1
home2
home3
home4

Projects
projects

About Us
aboutus

Events
events

All the test cases ran successfully.
Jest Output
jest-output

### Checklist:
**Delete irrelevant options.**
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@isabelcosta @vj-codes  Can you please review this PR. Thanks 🙂

**Review by isabelcosta — APPROVED** [review]
Great work @Rahulm2310 👏 🎉 !
Thank you for your contribution!

**Review by Vishal-raj-1 — APPROVED** [review]
LGTM

**Review by gaurivn — APPROVED** [review]
Good, Thank you

**Review by annabauza — APPROVED** [review]

**Pull request merged**
