### PR TITLE
Fix : Line breaks added at desired places

### PR DESCRIPTION
**Pull request by zyberg2091**
### Description

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes with reference to #192 

### Type of Change:

- Documentation formatting on homepage

**Code/Quality Assurance Only**

- This change requires a documentation update 

### How Has This Been Tested?

If you are working on a design then add a gif to show the responsiveness of your design.

- Already attested with issue #192 

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made changes to the documentation attested on issue #192

### CODE REVIEW

**Comment by nandini45** [comment]
@zyberg2091 it's great to see that u opened a PR as soon as u opened the issue. But 1st you have to wait for the maintainers of the project to approve and assign the issue to u .
Then only u can work on it further

**Comment by zyberg2091** [comment]
Sorry for the inconvenience caused @nandini45. can you check the PR?

**Comment by annabauza** [comment]
This issue has been assigned to @Amulya-coder

**Comment by annabauza** [comment]
This issue has been assigned to other Contributor.

**Pull request closed without merging**
