### PR TITLE
coding: fix the navbar collision in responsive view

### PR DESCRIPTION
**Pull request by prabhat04011998**
### Description

I have changed the margin of logo and closes the issue #166 

Fixes # [#166 ]

### Type of Change:
JUST A SIMPLE STYLE CHANGE

- Code
- Quality Assurance
- User Interface
- Outreach

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Already tested and deployed at 

https://prabhat04011998.github.io/anitab-org.github.io/

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have attached link of deployed site.
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by prabhat04011998** [comment]
Hey please check and approve @nandini45  @tichnas  @Bucky25 ,
i am working on the collapsable navbar.

**Comment by Bucky25** [comment]
@prabhat04011998 #174    has  been assigned  to u  .

**Comment by prabhat04011998** [comment]
@Bucky25  yes i am working on #174  and we can merge this in  meantime and close this issue after merging.

**Comment by gaurivn** [comment]
@prabhat04011998 , pls change the title of your PR to "coding: fix the navbar collision in responsive view" in accordance with [commit message style guide](https://github.com/anitab-org/mentorship-android/wiki/Commit-Message-Style-Guide).

**Comment by nandini45** [comment]
@Bucky25 can you review this PR ?

**Comment by tichnas** [comment]
I think this PR contains commits meant for another issue (#90)

**Review by tichnas — CHANGES_REQUESTED** [review]
I think this PR contains commits meant for another issue (#90)

**Comment by Bucky25** [comment]
@prabhat04011998 please make sure the changes made are solely of this issue only as it contains some changes to (#90) as @tichnas  mentioned remove these changes .
thanks for fixing the collision issue .

**Review by Bucky25 — CHANGES_REQUESTED** [review]
remove the changes which are not related to this issue.

**Review by annabauza — APPROVED** [review]

**Pull request merged**
