### PR TITLE
CODING: Develop the projects section on projects section 

### LINKED ISSUE #81: CODING: Develop the projects section on projects section
### Description
As a developer,
I need the following section of mockup to be developed,
so that I can add it in my projects page :  https://xd.adobe.com/view/e86737c2-ff84-4e23-b4b1-e541508d5279-bd34/

### mocks

spacing and all details

image

image

image

{font style-avenir color style-#103B81 Weight-medium}
### Acceptance Criteria

- [x] Follows all the design guidelines as mentioned and is responsive enough on large screen devices.
- [x] when clicked on ( view more ) all the listed projects should up .
- [x] the github and zulip redirect links should work in all  cards .

### Definition of Done

- [x]  All of the required items are completed.
- [x]  Approval by 2 mentor.

### Estimation
6 -7 hours

HAPPY CODING !! 😃

### PR DESCRIPTION
**Pull request by annabauza**
### Description

Create project section can be tested here:
https://annabauza.github.io/anitab-org.github.io/

Fixes #81

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Deployed changes https://annabauza.github.io/anitab-org.github.io/, tested manually.
Each user on card should be clickable, each zulip and github on card should be clickable.
View should be responsive.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by annabauza** [comment]
@raksh543 can you please approve if everything is fine. @anitab-org/qa-team  Can we make some testing as well 
https://annabauza.github.io/anitab-org.github.io/ ?

**Review by raksh543 — COMMENTED** [review]
@annabauza I tried ImageTextSection component in my code.
Using this, the image is appearing at the top of the image sub-container and not in center.

This is how it is looking:


Screenshot (157)


And according to the components i created, it looks like this:


Screenshot (158)

**Review by raksh543 — COMMENTED** [review]
Can you please suggest how to proceed?

**Comment by annabauza** [comment]
@raksh543 sure :)
1. Go to `Files changed`
2. Select `Review chanes`
3. Select one of the options `Comment`, `Approve` or `Request changes`

**Comment by annabauza** [comment]
@raksh543 we don't want it to be centred we want the image to be aligned with title.

**Comment by annabauza** [comment]
@anitab-org/coding-team can someone please review? Thanks!

**Review by raksh543 — COMMENTED** [review]
@annabauza The changes looks great if image is needed to be aligned with title.
It just needs some changes to incur responsiveness too.

**Comment by annabauza** [comment]
@raksh543 can you specify improvements or approve the PR please, so you could reuse the section?

**Review by raksh543 — CHANGES_REQUESTED** [review]
@annabauza Please make sure that the ImageTextSection is responsive.

**Comment by annabauza** [comment]
It is responsive, testing team was testing the link and said it is responsive. Out top menu and footer is not and it breaks the page width. Please look at the screenshots @raksh543 
Screenshot 2020-09-04 at 09 49 18
Screenshot 2020-09-04 at 09 49 37
Screenshot 2020-09-04 at 09 49 57

**Review by raksh543 — APPROVED** [review]

**Pull request merged**
