### PR TITLE
Coding : Developed the New To Open Source Section of Contribute Page

### LINKED ISSUE #63: Coding: Develop the New To Open Source Section of Contribute Page
## Description
As a user,
I need the following section of the mockup to be developed,
so that I can add it as New To Open Source Component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks

(Only the section in the red box to be developed excluding navbar)

contribute part1

Font Size for heading NEW TO OPEN SOURCE: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81
Image Size:  width: 352px,  height: 562px

[Design Link For Development
](https://xd.adobe.com/view/b3ce723d-5bc6-45f5-7035-0a637d919751-c5ff/)

### Update
- [ ] Follows all the design guidelines as mentioned and is responsive enough on large screen devices

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-5 hours

### PR DESCRIPTION
**Pull request by Aaishpra**
### Description

 Developed the New To Open Source Section of Contribute Page ( Fully Responsive ).

Fixes #63

### Type of Change:

- Code

- User Interface

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
image
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Aaishpra** [comment]
@anna4j @annabauza @Sonal240 @nandini45 can someone please review this.

**Comment by Sonal240** [comment]
@Aaishpra may please make a small gif or so because the image is having some glitch and it would be easier for us to look into it

**Comment by Aaishpra** [comment]
> @Aaishpra may please make a small gif or so because the image is having some glitch and it would be easier for us to look into it

Sure!

**Review by Sonal240 — CHANGES_REQUESTED** [review]
LGTM just share a gif to support your code changes... Another thing that I noticed was that the image is not leveled (bottom part) with the content on its left... Maybe due some glitch but if it exists kindly rectify it

**Comment by Aaishpra** [comment]
> LGTM just share a gif to support your code changes... Another thing that I noticed was that the image is not leveled (bottom part) with the content on its left... Maybe due some glitch but if it exists kindly rectify it

Just added some margin, and I guess it is now on the same level with the content have a look
image

**Comment by Aaishpra** [comment]
@Sonal240 can you tell me how can I attach a gif here in the comments, actually I tried adding the gif by just copying and pasting the gif as we do for screenshots, but it didn't work.

**Comment by Sonal240** [comment]
Upload your gif or video on drive and give it's link here I think this should work 
Other thing the image is slightly stretched vertically due to which the image is not aligned with the last line of the content may you please look into it thanks 😊

**Comment by Aaishpra** [comment]
Hey, @Sonal240 I have actually used ImageContent component (also used in About Us page) for the image as it gives both better responsiveness and styling (in my view it adjust its height with the height of the content) so I can't really change the height of the image but I have adjusted the margin a bit more to make it in level with the content. Below is the link for the gif
https://drive.google.com/file/d/1TVzYpHVts_c-qtumMlmwQEkjzRPwvTMw/view?usp=sharing
Still, if you think the problem exists I can try another solution instead of using the ImageContent component for the styling of the image.
Below is the Screenshot of the About us page I think a similar problem exists in that also
image

**Comment by Sonal240** [comment]
Hmm I saw but it was merged maybe we'll put a new maintenance issue... I wanted the image height to  be equal to the content height...but anyways if you can implement it it's ok else its ready to merge... I'll tag the qa team for testing 
Also Anna had shared a testing link or so for this site you may test it if you want

**Comment by Sonal240** [comment]
Also in gif I didn't see the responsive thing

**Comment by Aaishpra** [comment]
> Also in gif I didn't see the responsive thing 

Oh sorry, would attach a new gif then for the responsiveness.

**Comment by Aaishpra** [comment]
> Hmm I saw but it was merged maybe we'll put a new maintenance issue... I wanted the image height to  be equal to the content height...but anyways if you can implement it it's ok else its ready to merge... I'll tag the qa team for testing 
> Also Anna had shared a testing link or so for this site you may test it if you want 

Sure, i guess it would be better like this as reusing a component is always a good option and the image height matches the contents height in this section by giving some margin between header and description, and would test the PR out if i am able to.

**Comment by Aaishpra** [comment]
> Also in gif I didn't see the responsive thing
Here is the gif for responsive design
https://drive.google.com/file/d/1tRNbKqX8rfzJg0rl8VBceqHJmbkeBxgp/view?usp=sharing

**Comment by Sonal240** [comment]
@anitab-org/qa-team Kindly test the code and approve it.... Thanks😊

**Comment by nandini45** [comment]
@Aaishpra  can you tell me about the content ? where is it from?

@Sonal240  i think the image looks a bit stretched for design and contribute section has a lot of things in  it if just a small portion is this big it will be a problem 
and i think you should reduce the content a bit 
. other than that its good

**Comment by nandini45** [comment]
and one more thing i think in the responsiveness gif you should show how the screen will look in web and mobile view
try dragging the cursor left right not up down.

**Comment by Aaishpra** [comment]
> and one more thing i think in the responsiveness gif you should show how the screen will look in web and mobile view
> try dragging the cursor left right not up down. 

Will attach a new gif for that

**Comment by Sonal240** [comment]
I am not happy with most of the issues because of the content length... look for example the homepage section itself ...idk what should I say @nandini45 the content though looks appealing but the length doesn't

**Comment by nandini45** [comment]
@Sonal240  agreed. i will see into it.
for now i think we need to edit the content

**Comment by Aaishpra** [comment]
> and one more thing i think in the responsiveness gif you should show how the screen will look in web and mobile view
> try dragging the cursor left right not up down.

Have a look @nandini45

**Comment by Aaishpra** [comment]
Hey @Sonal240 and @nandini45 is there anything else remaining in the PR,Are you people going to edit the content? Or any other change just curious.

**Comment by Sonal240** [comment]
The coding part is done from your side only the content is to be altered...

**Comment by Aaishpra** [comment]
> The coding part is done from your side only the content is to be altered... 

Sure, Thanks for clarifying.😊

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@Aaishpra please see my request below

**Comment by devkapilbansal** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Test1 Description_  Tested responsiveness of the design
     _Screenshot/gif_:  
change needed

     _Expected Result_:  Design should be responsive to different screen sizes.
     _Actual Result_: For some screen sizes, image is overflowing outside. For eg:- 768*1024(screen size)
    _Test Result_: Failed

4. Additional Comments: Changes Requested.

**Comment by Aaishpra** [comment]
@devkapilbansal i am a bit busy with my exams so i would require some time to change the pr as you requested. Thanks for testing this PR , also can you test this one also https://github.com/anitab-org/open-source-programs-web/pull/57#issue-475773022

**Comment by devkapilbansal** [comment]
> @devkapilbansal i am a bit busy with my exams so i would require some time to change the pr as you requested. Thanks for testing this PR , also can you test this one also [anitab-org/open-source-programs-web#57 (comment)](https://github.com/anitab-org/open-source-programs-web/pull/57#issue-475773022)

Noted. Will test it soon

**Review by annabauza — APPROVED** [review]

**Comment by devkapilbansal** [comment]
@annabauza I tested it locally and found some responsivity bugs. Just want to enquire why this pull request is merged without changes as requested. @rpattath changed the label too for thjs

**Comment by annabauza** [comment]
> @annabauza I tested it locally and found some responsivity bugs. Just want to enquire why this pull request is merged without changes as requested. @rpattath changed the label too for this

Please rise the issue this PR has been merged alredy

**Pull request merged**
