### PR TITLE
Revert "Coding: Meet Our Open Source Community Part Of About Page "

### PR DESCRIPTION
**Pull request by Sonal240**
Reverts anitab-org/anitab-org.github.io#95

### CODE REVIEW

**Comment by Sonal240** [comment]
@anna4j I'm reverting it because I saw that the members_profile_data.json file is not in content folder...kindly do that and then I'll merge it..sorry for the inconvenience caused

**Comment by anna4j** [comment]
@Sonal240 No problem! I've added the file to content folder

**Comment by Sonal240** [comment]
@nandini45 may you please approve this pr and merge it...I forgot to tell @anna4j that the JSON file needs to be in the content folder and I merged it...she has raised another pr by making necessary changes and I have reviewed it as well...sorry for the inconvenience caused...

**Comment by Sonal240** [comment]
It would revert the commit that @anna4j  had made (one that I had merged by mistake)...

**Pull request merged**
