### PR TITLE
content: Added badges in README

### LINKED ISSUE #112: content: add badge in the README.md
### Description
As a developer,
I need to see the badges symbolising the our communication channel

### Acceptance Criteria
Update [Required]
Add badges

### Definition of Done

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

### Estimation
30 min

### PR DESCRIPTION
**Pull request by jivthesh**
Description
Created badges in README.md

Fixes #112 

Type of Change:
Delete irrelevant options.

Documentation

Code/Quality Assurance Only
This change requires a documentation update (software upgrade on readme file)

Delete irrelevant options.

**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by nandini45** [comment]
@jivthesh  thanks for the contribution but can you edit the pull request template

**Comment by nandini45** [comment]
so that the reviewer understand what this PR is about'

**Comment by jivthesh** [comment]
@nandani45 can u edit that as per the template

**Comment by jivthesh** [comment]
@nandini45 can u edit as per the template

**Comment by annabauza** [comment]
@jivthesh please update title and description to fit AnitaB standards, other then that the PR is good

**Comment by jivthesh** [comment]
@annabauza done !please check

**Comment by annabauza** [comment]
no it does not. please have a look at this PR https://github.com/anitab-org/anitab-org.github.io/pull/86 for example

**Comment by annabauza** [comment]
please check [PR template](https://github.com/anitab-org/anitab-org.github.io/blob/develop/.github/PULL_REQUEST_TEMPLATE.md). thanks!

**Comment by jivthesh** [comment]
@annabauza done now

**Comment by annabauza** [comment]
title should have `content:` prefix

**Comment by jivthesh** [comment]
@annabauza done

**Comment by annabauza** [comment]
@jivthesh if it is done please change labels from `changes requested` to `require review`

**Comment by jivthesh** [comment]
@annabauza how can i edit label i am not able to change .changes have been done

**Pull request merged**
