### PR TITLE
docs: PR Template in CONTRIBUTING.md is corrected

### LINKED ISSUE #230: PR Template in CONTRIBUTING.md doesn't exist
### Describe the bug
PR Template in CONTRIBUTING.md doesn't exist

### To Reproduce
1. Go to 'https://github.com/anitab-org/anitab-org.github.io/blob/develop/CONTRIBUTING.md'
2. Scroll down to 'Contributing Guidelines'
3. Click on 'this template '

### Expected behavior
Should direct to PR template

### Screenshots
image

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Firefox
 - Version 85.0.1 (64-bit)

### PR DESCRIPTION
**Pull request by shruti1421**
### Description
Now, if we click "this template" in CONTRIBUTING.md file PR template page opens successfully.

Fixes #230

### Type of Change:
**Delete irrelevant options.**
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rahulm2310 — APPROVED** [review]
LGTM 💯

**Comment by shruti1421** [comment]
@Rahulm2310 Now, you can check I've added the correct link in docs/CONTRIBUTING.md file too.

**Review by jhalak27 — APPROVED** [review]
Works fine

**Comment by Rahulm2310** [comment]
Working!. @shruti1421 just a suggestion. Both of your commits have the same commit message. Please be more specific regarding the commit messages like what this commit is fixing or changing. For now, thanks for your contribution 🎉

**Comment by Rahulm2310** [comment]
@keshakaneria As this PR already has 2 reviews, it is ready to merge.

**Comment by keshakaneria** [comment]
> @keshakaneria As this PR already has 2 reviews, it is ready to merge.

We followed this in OSH program last time if it has 2 reviews, then for final check by the maintainers to merge them so I added the same. Correct me if I'm wrong😄

**Comment by annabauza** [comment]
@shruti1421 can you resolve conflicts please

**Comment by isabelcosta** [comment]
I will close this PR due to lack of activity. Thank you @shruti1421 for contributing 🤗

**Pull request closed without merging**
