### PR TITLE
Added a section of home page

### LINKED ISSUE #110: Coding: Develop the following section for Home Page
### Is your feature request related to a problem? Please describe.
As a developer,
I need the following section to be developed so that I can add is as a Home component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components)

### Mocks
Develop this section only

Screenshot (28)_LI

Font Size for heading EVENTS: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81

[Design link for development](https://xd.adobe.com/view/09a9fdf0-a193-4b3f-47c2-216055c7ca42-7f98/)

### Update [Required]
- [ ] Should follow all the margin guidelines mentioned above and should be responsive

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-8 hours

### PR DESCRIPTION
**Pull request by raksh543**
### Description

Added the home section of Getting started, ways to contribute, our projects and open source programs

Fixes #110

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I have checked the responsiveness by resizing window.

Landscape view:
b

Potrait view:
a

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by annabauza** [comment]
@raksh543 please separate this to 4 sections and each section should follow our [implementation guide](https://github.com/anitab-org/anitab-org.github.io/wiki/Implementation-guide). Thanks.

**Review by annabauza — CHANGES_REQUESTED** [review]
@raksh543 please separate this to 4 sections and each section should follow our [implementation guide](https://github.com/anitab-org/anitab-org.github.io/wiki/Implementation-guide). Thanks.

**Comment by annabauza** [comment]
@raksh543 I had something bit more reusable in my mind. Can you please review this [PR](https://github.com/anitab-org/anitab-org.github.io/pull/135) There is ImageTextSection which you could just use? Thanks in advance. I think I will need to add paragraphs to keep consistency.

**Comment by annabauza** [comment]
@raksh543 I have applied the changes, can you please review?

**Review by raksh543 — COMMENTED** [review]
@annabauza I have reviewed the changes.
It looks good.

**Comment by annabauza** [comment]
@raksh543 the PR has been merged so you can reuse TextImage component. Please prepare testing page by following the guide https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR

**Comment by raksh543** [comment]
@annabauza Please check the [preview](https://raksh543.github.io/anitab-org.github.io/) of the webpage, if it looks fine now i will proceed.

**Comment by raksh543** [comment]
@annabauza Please review the changes

**Review by annabauza — CHANGES_REQUESTED** [review]
1. No need to add other fonts,
2. image requests should come from content - look on how other code parts are solving it - replace json with js file
3. page should not display on each tab - only when you press on AnitaB logo (if case 0 in Content.js)
4. use styled view like aboutus/styles.js
5. use mapper instead of create each section file separately.
6. remove dependency which you have added.

**Comment by raksh543** [comment]
@annabauza I am working on these changes.
Will update soon.

**Comment by raksh543** [comment]
@annabauza I have made all changes as requested. Please review.

**Review by annabauza — CHANGES_REQUESTED** [review]
@raksh543 thank you for this PR, I have added those sections can you please update the images on home page? Thanks!

**Comment by nandini45** [comment]
@raksh543 can u do the changes??
Do update us asap if not I have to assign this issue to someone else.

**Comment by raksh543** [comment]
@nandini45 Sure i will do the changes. Please tell me which which images i am supposed to change.

**Comment by Vishal-raj-1** [comment]
@anna4j Any update on this PR? I can see this PR contains many conflicting files. Please resolve conflicts and you can squash your 19 commits to single commit. Thanks !!

**Comment by annabauza** [comment]
closing this issue because getting started already exists.

**Pull request closed without merging**
