### PR TITLE
Gh pages

### LINKED ISSUE #166: Fix: the Navbar Collision in responsive View(Logo and About-us tab)
### Describe the bug
The Responsive view of website leads to distortion in navbar(Header).

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on inspect->mobile view icon
3. Scroll up (Upto top)
4. See error( logo and about us us tab colliding)

### Expected behavior
This about us and logo should not collide.

### Screenshots

issue_in_responsive_view

### Desktop (please complete the following information):
 - OS: [Linux 20+]
 - Browser [Firefox]
 - Version [83.0]

### Smartphone (please complete the following information):
 - Device: [Xiomi ]
 - OS: [android]
 - Browser [chrome]
 - Version [latest]

### Additional context
It's the issue of front-end (User Interface).
Some styling needs to fix.

### PR DESCRIPTION
**Pull request by prabhat04011998**
### Description

I have fixed the issue #166  .
My pr closes #166 

Fixes #166 ]

### Type of Change:
nothing required

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
here is the deployed link
https://prabhat04011998.github.io/anitab-org.github.io/

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have attached link of deployed site.

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by prabhat04011998** [comment]
I have fixed the issue #166 please check.

**Comment by nandini45** [comment]
@prabhat04011998  great.
 @Bucky25 can you review this one?

**Comment by nandini45** [comment]
@prabhat04011998  can you check your travis build its failing

**Comment by Bucky25** [comment]
@prabhat04011998 you have made pr to merge gh-pages branch to main develop of repo which is not correct  .
you have to make pr to merge the changes made in cloned repo .

**Comment by Bucky25** [comment]
@prabhat04011998 you can make new pr . we will review that .
as @nandini45 you can close it

**Review by Bucky25 — CHANGES_REQUESTED** [review]
please follow the contribution guidelines and gh-pages is only for deploying and seeing if it's working correctly on all screens

**Comment by prabhat04011998** [comment]
@Bucky25  okay i'll recreate the PR.

**Comment by prabhat04011998** [comment]
@Bucky25  i am not able to create PR , i already have a pr which not merged yet , so it's not allowing to make an PR ,any idea about it?

**Comment by tichnas** [comment]
@prabhat04011998 It's always a good practice to create different branches for each issue. Also, this will allow you to create another PR.

Switch to new branch locally: `git checkout -b <branch>`
Push the beach to GitHub: `git push -u origin <branch>`

Do let me know if you face any more issues :)

**Pull request closed without merging**
