### PR TITLE
refactor: replace capital letters with normal letters on our navbar

### LINKED ISSUE #295: [Refactor] Update our navigation bar converting all capital letters to normal text
### Describe the situation
We are using in our navigation bar all texts as capital letters and this brings some special problems for (screen readers & search engines).

### To Reproduce
Steps to reproduce the behaviour:
1. Go to our website
2. Look for the navigation bar (check the image below)

image

### Expected behaviour
At the end of the day we should have the same result, but using the proper properties in our code.

### Desktop (please complete the following information):
 - OS: MacOS
 - Browser: https://www.whatsmybrowser.org/b/LI5WH

### PR DESCRIPTION
**Pull request by ftonato**
### Description

In order to fix the problem related on the issue #295 I've created the code to fix it.

Fixes #295

### Type of Change:

- Code

### How Has This Been Tested?
You can run the new branch and check if all navigation items are with "capital letters".

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by isabelcosta** [comment]
@brittanyjoiner15 could you please approve it again :) Approve is one of the review options. After that I can merge :)

**Comment by isabelcosta** [comment]
@brittanyjoiner15 do you know what could be wrong with prettier run here? I don't think it is related to this PR 🤔 But I am not sure
cc @Aaishpra @codesankalp in case you have some useful knowledge here on github actions in web projects

@ftonato do you have an idea of what could be happening here? I updated this PR in hopes it would be mergable right away, but this check is failing. Could we do something here 🤔

**Comment by brittanyjoiner15** [comment]
@ftonato @isabelcosta hmm, I wonder if it's because it's confused because we have the `.prettierrc.json` file merged in but this branch doesn't have it yet? Maybe @ftonato try pulling changes from`develop` and seeing if it works after that's all merged up together?

**Comment by ftonato** [comment]
Hello, after a few minutes of trying and trying I found the problem, or at least managed to fix it on my branch.

I'll open a pull-request to submit the solution and remove the commits I made on the current branch to test...

> btw, we should have a telegram channel to talk about a few things (all three)!

/c @isabelcosta @brittanyjoiner15

**Comment by ftonato** [comment]
**I just deleted all commits, I'm going to redo them (dumb)!**

**Comment by isabelcosta** [comment]
> btw, we should have a telegram channel to talk about a few things (all three)

We can talk on [Zulip](https://anitab-org.zulipchat.com ) :) That is where the community talks about the projects so that everyone can join discussions. We have a stream for this project.

**Comment by isabelcosta** [comment]
> I don't understand why it's failing only on the pull-request and not on my branch (fork), I'll need to invest a little more time on this tomorrow to calmly evaluate...
> 
> I will do this as soon as possible!

I see it falling on your fork as well https://github.com/ftonato/anitab-org.github.io/runs/3919521463 🤔  but take your time! As long as we have updates from time to time.

**Comment by isabelcosta** [comment]
> I don't understand why it's failing only on the pull-request and not on my branch (fork), I'll need to invest a little more time on this tomorrow to calmly evaluate...
> 
> I will do this as soon as possible!

I see it falling on your fork as well https://github.com/ftonato/anitab-org.github.io/runs/3919521463 🤔  but take your time! As long as we have updates from time to time.

**Pull request closed without merging**
