### PR TITLE
About Us page

### LINKED ISSUE #51: Coding: Develop the following About Us Page
## Description
As a developer,
I need the following attached About Us mock-up to be implemented,
so that I can add it as an About Us Component [here ](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks
(Only the section in the red box avoid navbar as it is already developed)
about-us-part1

NOTE:
The horizontal lines in insights are downloadable assets..kindly go through design development link shared
The horizontal gutter between the lines mentioned above and the description (the one which is left aligned and next to it) is 16pt
The margin between heading and description: 8pt
Font Size for headings: Header Medium(32pt) weight- Medium 
Font Style-Avenir
Font Size for the description below including the learn more link: body 18pt weight- Light
Font Color (headings): #103B81
Font Color (Body): #103B81
Font Color (Learn More): #103B81

[Design Link for Development](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/)

### Update [Required]
- [ ] When a user clicks Learn More Link (below OUR HISTORY) redirect them[ here](https://anitab.org/about-us/mission-and-history/)
- [ ] When a user clicks Learn More Link (below ABOUT ANITA BORG) redirect them[ here](https://anitab.org/about-us/about-anita-borg/)
- [ ] When a user scrolls down to INSIGHTS a countUp effect should be implemented.
- [ ] Please go through the Development link shared with mock-up for margin guidelines, also the side image's height should extend till insights, as mentioned in mock-up and text, should be adjusted according to the image.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by devRD**
### Description

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #51

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Sonal240** [comment]
@devRD can you add a gif that shows all the changes that you have done including in responsive view...thanks

**Comment by nandini45** [comment]
@devRD  can you make the changes as suggested. and update your work

**Comment by devRD** [comment]
I apologise for the inconvenience, I'll close this PR and someone can make the issue available again. I'm unable to take time out to complete this at the moment. :/

**Comment by nandini45** [comment]
@Sonal240  have a look here? 
 i reopened the issue

**Pull request closed without merging**
