### PR TITLE
style: Add prettier and github action

### LINKED ISSUE #293: Add a code linter and it's github action
### Is your feature request related to a problem? Please describe.
Different contributors have different code styles, so when merging the code we need to make sure the code is consistent.
Like Black is a linter for python, use Prettier or Eslint in this project.

### Describe the solution you'd like
Integrate either Prettier.io (https://prettier.io/) or Eslint(https://eslint.org/), format and push the updated code and 
add GitHub action to check the formatting using either of the two.

### PR DESCRIPTION
**Pull request by brittanyjoiner15**
### Description

Add prettier and github action

Fixes #293 

### Type of Change:

- Code

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

_no designs - this is just code formatting_

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes -- I noticed a couple tests didn't pass, but it doesn't look like it's because of formatting, such as `project.test.js` , the `should take snapshot 1` doesn't pass because it's expecting a width of 24 px and receiving a width of 32 px;
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by brittanyjoiner15** [comment]
@codesankalp looks like i need another approval on the PR before i can merge?
image

**Comment by brittanyjoiner15** [comment]
@isabelcosta okay i just pushed another change, can you try to approve it again and see what happens?

**Comment by brittanyjoiner15** [comment]
@isabelcosta dangit. I'm still not sure why it's not working.  @codesankalp do you have any ideas?

**Comment by isabelcosta** [comment]
Nice shout out to @codesankalp 
I have no idea either 😓 But you did progress a bit, I see the checks are at least running now.
(I'll have to go now, but really like your proactiveness here! 💪🏾 @brittanyjoiner15 )

**Comment by brittanyjoiner15** [comment]
@isabelcosta when you're back online, can you try to run it again? i might have figured it out - i think the `with`/`ref` statement. Confirmed with some other colleagues this is not always necessary and could be what's breaking it.

**Pull request merged**
